Description: >
  This template deploys Grafana to an AWS Fargate Cluster on
  user-defined VPC and Subnets. Container definition is pulled from
  the public Docker image for Grafana
  (https://hub.docker.com/r/grafana/grafana/). An ECS Service ensures
  Grafana continues to run on the created Cluster. Logging is captured
  within CloudWatch.

Parameters:
  VpcId:
    Description: The VPC to which this cluster should be deployed
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: Choose at least two subnets in this VPC
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/grafana-fargate
  
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: grafana-fargate-cluster

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grant access to Grafana
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  OpenTSDBRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      #SourceSecurityGroupId: !Ref SecurityGroup
      CidrIp: 0.0.0.0/0
      IpProtocol: tcp
      FromPort: 4242
      ToPort: 4242
      GroupId: !Ref SecurityGroup
      
  TaskDefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: grafana-fargate-demo
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      Memory: '512'
      Cpu: '256'
      ContainerDefinitions:
        - Name: grafana-container
          Image: grafana/grafana
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
                awslogs-group: "/ecs/grafana-fargate"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "dashboard"

  ServiceDefinition:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      Cluster: !Ref ECSCluster
      ServiceName: grafana-dashboard-service
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets
          SecurityGroups:
            - !Ref SecurityGroup

  OpenTSDBTaskDefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: opentsdb-fargate-demo
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      Memory: '512'
      Cpu: '256'
      ContainerDefinitions:
        - Name: opentsdb-container
          Image: petergrace/opentsdb-docker
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 4242
          LogConfiguration:
            LogDriver: awslogs
            Options:
                awslogs-group: "/ecs/grafana-fargate"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "dashboard"

  OpenTSDBServiceDefinition:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      TaskDefinition: !Ref OpenTSDBTaskDefinition
      Cluster: !Ref ECSCluster
      ServiceName: opentsdb-dashboard-service
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets
          SecurityGroups:
            - !Ref SecurityGroup
